[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
lefi = { path = "../scripting" }
rocket = { version = "0.5.1", features = ["json"] }
serde_json = "1.0.70"
serde = { version = "1.0", features = ["derive"] }
